import { describe, it, expect } from "vitest";
import { Fr } from "@aztec/foundation/fields";
import { Point } from "@zk-kit/baby-jubjub";
import { deriveCek, computePsi, leaf, LeanIMT } from "@hisoka/wallets";
import { proveSwapIntent } from "../provers/kage/swapIntent.js";
import {
  proveSwapSettle,
  nativeBbAvailable,
} from "../provers/kage/swapSettle.js";
import { SwapIntentInputs, NoteInput } from "../types.js";

// Regenerates evm-contracts/test/integration/kageGolden.ts (native bb only, opt-in):
//   cd packages/prover && GEN_KAGE_GOLDEN=1 KAGE_NATIVE=1 npx vitest run src/__tests__/gen-kage-golden.test.ts
// Paste the emitted block over kageGolden.ts; re-run with the verifiers from the SAME build.
const OPT_IN = process.env.GEN_KAGE_GOLDEN === "1";
const runnable = OPT_IN && nativeBbAvailable();
if (OPT_IN && !runnable) {
  console.warn(
    "[gen-kage-golden] GEN_KAGE_GOLDEN=1 but native bb unavailable -- skipping.",
  );
}

// GENESIS is DarkPool's chain-bound leaf 0 for chainId 31337; the golden root needs exactly this seed.
const C: Point<bigint> = [
  0x085ed469c9a9f102b6d4f6f909b8ceaf6ca49b39759ac2e0feb7e0aada8b7111n,
  0x245e25ab2bd42f0280a5ade750828dd6868f5225ae798d6b51c676f519c8f4e8n,
];
const GENESIS = new Fr(
  0x12f144d31019d46ff993f3fe3b8a001a0d606ea4b1140525ed615a4402066372n,
);
const FROM_ASSET = 0x1234567890123456789012345678901234567890n;
const TO_ASSET = 0xabcdefabcdefabcdefabcdefabcdefabcdefabcdn;
const OWNER = new Fr(
  0x2874ae964d8b283e2f521a7f14125fc92747bb9770139b8d4b70ee09e2d83785n,
);
const SPEND_SCALAR = new Fr(789n);
const CURRENT_TIMESTAMP = new Fr(0xf4865700n);
const EXPIRY = new Fr(0xf4865800n);

const psiOf = async (eph: bigint): Promise<Fr> =>
  computePsi(deriveCek(new Fr(eph), C));

const note = (
  asset: bigint,
  value: bigint,
  psi: Fr,
  parents: bigint,
): NoteInput => ({
  noteVersion: new Fr(1n),
  assetId: new Fr(asset),
  noteType: new Fr(0n),
  conditionsHash: new Fr(0n),
  value: new Fr(value),
  owner: OWNER,
  psi,
  parents: new Fr(parents),
});

const leafOf = async (
  asset: bigint,
  value: bigint,
  psi: Fr,
  parents: bigint,
): Promise<Fr> =>
  leaf({
    noteVersion: new Fr(1n),
    assetId: new Fr(asset),
    noteType: new Fr(0n),
    conditionsHash: new Fr(0n),
    value,
    owner: OWNER,
    psi,
    parents: new Fr(parents),
  });

const hex = (f: Fr | bigint): string =>
  "0x" +
  (typeof f === "bigint" ? f : f.toBigInt()).toString(16).padStart(64, "0");

(runnable ? describe : describe.skip)(
  "regenerate the Kage golden vector",
  () => {
    it("emits a fresh native-bb swap_settle proof over the genesis-seeded fixture", async () => {
      const takerInPsi = await psiOf(111n);
      const makerInPsi = await psiOf(222n);
      const leafA = await leafOf(FROM_ASSET, 100n, takerInPsi, 0n);
      const leafB = await leafOf(TO_ASSET, 100n, makerInPsi, 0n);

      const tree = new LeanIMT(32);
      await tree.insert(GENESIS);
      await tree.insert(leafA);
      await tree.insert(leafB);
      const root = tree.getRoot();

      const intentInputs: SwapIntentInputs = {
        compliancePk: C,
        noteIn: note(FROM_ASSET, 100n, takerInPsi, 0n),
        spendScalar: SPEND_SCALAR,
        indexIn: 1,
        pathIn: tree.getMerklePath(1),
        changeNote: note(FROM_ASSET, 40n, await psiOf(9n), 1n),
        changeEph: new Fr(9n),
        receivedNote: note(TO_ASSET, 50n, await psiOf(15n), 1n),
        receivedEph: new Fr(15n),
        toAsset: new Fr(TO_ASSET),
        fromAmount: new Fr(60n),
        expiry: EXPIRY,
      };
      const intent = await proveSwapIntent(intentInputs);

      const settled = await proveSwapSettle({
        compliancePk: C,
        currentTimestamp: CURRENT_TIMESTAMP,
        makerNoteIn: note(TO_ASSET, 100n, makerInPsi, 0n),
        makerSpendScalar: SPEND_SCALAR,
        makerIndex: 2,
        makerPath: tree.getMerklePath(2),
        makerReceived: note(FROM_ASSET, 60n, await psiOf(20n), 2n),
        makerReceivedEph: new Fr(20n),
        makerChange: note(TO_ASSET, 50n, await psiOf(28n), 2n),
        makerChangeEph: new Fr(28n),
        intent,
      });

      expect(settled.verified).toBe(true);
      expect(settled.publicInputs.length).toBe(42);
      expect(settled.publicInputs[5]).toBe(hex(root));

      const proofHex = "0x" + Buffer.from(settled.proof).toString("hex");
      const lines = [
        "// GENERATED by packages/prover/src/__tests__/gen-kage-golden.test.ts -- do not hand-edit.",
        `export const KAGE_PROOF =\n  "${proofHex}";`,
        "",
        "export const KAGE_PUBLIC_INPUTS: string[] = [",
        ...settled.publicInputs.map((p) => `  "${p}",`),
        "];",
        "",
        `export const KAGE_GENESIS =\n  "${hex(GENESIS)}";`,
        "",
        `export const KAGE_LEAF_A =\n  "${hex(leafA)}";`,
        "",
        `export const KAGE_LEAF_B =\n  "${hex(leafB)}";`,
        "",
        `export const KAGE_GOLDEN_ROOT =\n  "${hex(root)}";`,
      ];
      console.log(
        "\n=====KAGE_GOLDEN_BEGIN=====\n" +
          lines.join("\n") +
          "\n=====KAGE_GOLDEN_END=====\n",
      );
    }, 1_800_000);
  },
);
