[package]
name = "transfer_multisig"
type = "bin"
authors = ["hisoka-io"]
license = "Apache-2.0"

[dependencies]
shared = { path = "../../shared" }
ecdh = { tag = "ecdh-v0.0.2-hisoka.1", git = "https://github.com/hisoka-io/zk-kit.noir", directory = "packages/ecdh" }
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }
