import { UltraHonkBackend, Barretenberg } from "@aztec/bb.js";
import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
} from "fs";
import { execFileSync } from "child_process";
import { resolve, dirname, join } from "path";
import { tmpdir, homedir } from "os";
import { fileURLToPath } from "url";
import { CIRCUITS, KAGE_CIRCUITS } from "./circuits.js";

// swap_settle's Solidity verifier is generated by native bb (bb.js WASM cannot verify-gen a recursion circuit).
// Guarded: regenerate + assert byte-identical where native bb is present; skip (keep the committed verifier) where
// it is absent, so the base build stays green on bb.js-only CI.
function regenerateKageVerifier(circuitsDir, verifiersDir) {
  const kage = KAGE_CIRCUITS.find((c) => c.verifier);
  if (!kage) return;
  const bbPath = process.env.BB_NATIVE_PATH ?? resolve(homedir(), ".bb", "bb");
  const wantVersion = "4.0.0-nightly.20260218";
  let version = "";
  try {
    version = execFileSync(bbPath, ["--version"], { encoding: "utf8" }).trim();
  } catch {
    version = "";
  }
  if (!version.includes(wantVersion)) {
    console.log(
      `[skip] native bb ${wantVersion} not found at ${bbPath}; keeping committed ${kage.verifier}`,
    );
    return;
  }
  const bytecode = resolve(circuitsDir, "target", `${kage.name}.json`);
  const tmp = mkdtempSync(join(tmpdir(), "kage-vk-"));
  try {
    execFileSync(bbPath, ["write_vk", "-b", bytecode, "-o", tmp, "-t", "evm"], {
      stdio: "pipe",
    });
    const genPath = join(tmp, kage.verifier);
    execFileSync(
      bbPath,
      [
        "write_solidity_verifier",
        "-k",
        join(tmp, "vk"),
        "-o",
        genPath,
        "-t",
        "evm",
      ],
      { stdio: "pipe" },
    );
    const committed = resolve(verifiersDir, kage.verifier);
    const gen = readFileSync(genPath);
    if (
      existsSync(committed) &&
      Buffer.compare(gen, readFileSync(committed)) !== 0
    ) {
      throw new Error(
        `native-generated ${kage.verifier} differs from committed -- swap_settle VK moved`,
      );
    }
    writeFileSync(committed, gen);
    console.log(`Regenerated ${kage.verifier} via native bb (byte-identical).`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const circuitPackagesNames = CIRCUITS.map((c) => c.name);
const circuitsDir = resolve(__dirname, "../../circuits");
const artifactsPath = circuitPackagesNames.map((circuitPackageName) =>
  resolve(circuitsDir, "target", `${circuitPackageName}.json`),
);

const contractsDir = resolve(__dirname, "../../evm-contracts/contracts");
const verifiersDir = resolve(contractsDir, "verifiers");
const outputPath = CIRCUITS.map((c) => resolve(verifiersDir, c.verifier));
const vkHashManifestPath = resolve(verifiersDir, "vk-hashes.json");
const vkHashes = {};

async function main() {
  console.log("--- Generating Solidity Verifiers ---");

  for (
    let circuitIndex = 0;
    circuitIndex < circuitPackagesNames.length;
    circuitIndex++
  ) {
    const artifactPath = artifactsPath[circuitIndex];
    if (!existsSync(artifactPath)) {
      console.error(`[Error] Circuit artifact not found at ${artifactPath}.`);
      console.error(
        'Please run "pnpm build" in the "prover" package first to compile the circuit.',
      );
      process.exit(1);
    }

    const circuitJson = JSON.parse(readFileSync(artifactPath, "utf8"));
    const api = await Barretenberg.new({ threads: 8 });
    const backend = new UltraHonkBackend(circuitJson.bytecode, api);

    try {
      const verificationKey = await backend.getVerificationKey({
        verifierTarget: "evm",
      });
      const verifierString = await backend.getSolidityVerifier(
        verificationKey,
        { verifierTarget: "evm" },
      );

      const vkHashMatch = verifierString.match(
        /uint256 constant VK_HASH = (0x[0-9a-fA-F]{64});/,
      );
      if (!vkHashMatch) {
        console.error(
          `[Error] VK_HASH not found in the generated verifier for "${circuitPackagesNames[circuitIndex]}".`,
        );
        process.exit(1);
      }
      vkHashes[circuitPackagesNames[circuitIndex]] = vkHashMatch[1];

      console.log(`Writing ${outputPath[circuitIndex]}...`);

      if (!existsSync(verifiersDir)) {
        mkdirSync(verifiersDir, { recursive: true });
      }
      writeFileSync(outputPath[circuitIndex], verifierString);
    } catch (error) {
      console.error("[Error] Failed to generate Solidity Verifier:", error);
      process.exit(1);
    } finally {
      await api.destroy();
    }
  }

  writeFileSync(vkHashManifestPath, JSON.stringify(vkHashes, null, 2) + "\n");
  console.log(`Wrote VK-hash manifest: ${vkHashManifestPath}`);

  regenerateKageVerifier(circuitsDir, verifiersDir);
}

main();
