import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
} from "fs";
import { execFileSync } from "child_process";
import { resolve, dirname, join } from "path";
import { tmpdir, homedir } from "os";
import { fileURLToPath } from "url";
import { CIRCUITS, KAGE_CIRCUITS } from "./circuits.js";

// All Solidity verifiers are generated by native bb 5.0 with `--optimized` (the sub-$1 ZK-Honk verifier), which is
// CLI-only -- bb.js hardcodes optimizedSolidityVerifier:false. Proofs are still produced by bb.js; barretenberg
// #1649 (bb.js VK == CLI VK) makes a bb.js proof verify against this CLI verifier. The --optimized verifier is a
// self-contained monolithic contract (no externalized ZKTranscriptLib) and fits EIP-170 on its own.
//
// Circuit-change runbook (after editing any .nr): run `pnpm build` in packages/prover WITH native bb 5.0 on the
// path (BB_NATIVE_PATH or ~/.bb/bb) so this script rewrites the affected verifier .sol + vk-hashes.json; then
// commit the regenerated verifiers + vk-hashes.json AND re-bless vk-hashes.golden.json to the new hashes. Without
// native bb this step is skipped (committed verifiers kept) and the prover VK-parity guard fails on the drift, so
// a circuit change must never be committed without a native-bb regen.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const BB_PATH = process.env.BB_NATIVE_PATH ?? resolve(homedir(), ".bb", "bb");
const BB_VERSION = "5.0.0";

const circuitsDir = resolve(__dirname, "../../circuits");
const contractsDir = resolve(__dirname, "../../evm-contracts/contracts");
const verifiersDir = resolve(contractsDir, "verifiers");
const vkHashManifestPath = resolve(verifiersDir, "vk-hashes.json");

function assertNativeBb() {
  let version = "";
  try {
    version = execFileSync(BB_PATH, ["--version"], { encoding: "utf8" }).trim();
  } catch {
    throw new Error(
      `native bb not found at ${BB_PATH} (set BB_NATIVE_PATH; install via bbup -v ${BB_VERSION}). ` +
        `--optimized verifier generation is CLI-only, so native bb is required.`,
    );
  }
  if (!version.includes(BB_VERSION)) {
    throw new Error(
      `native bb version mismatch: got ${version} want ${BB_VERSION}`,
    );
  }
}

function generateOne(name, verifier) {
  const bytecode = resolve(circuitsDir, "target", `${name}.json`);
  if (!existsSync(bytecode)) {
    throw new Error(
      `Circuit artifact not found at ${bytecode}. Run "pnpm build" in the prover package first.`,
    );
  }
  const tmp = mkdtempSync(join(tmpdir(), "vk-"));
  try {
    execFileSync(
      BB_PATH,
      ["write_vk", "-b", bytecode, "-o", tmp, "-t", "evm"],
      { stdio: "pipe" },
    );
    const outPath = resolve(verifiersDir, verifier);
    execFileSync(
      BB_PATH,
      [
        "write_solidity_verifier",
        "-k",
        join(tmp, "vk"),
        "-o",
        outPath,
        "-t",
        "evm",
        "--optimized",
      ],
      { stdio: "pipe" },
    );
    const src = readFileSync(outPath, "utf8");
    const m = src.match(/uint256 constant VK_HASH = (0x[0-9a-fA-F]{64});/);
    if (!m) throw new Error(`VK_HASH not found in generated ${verifier}`);
    console.log(
      `Wrote ${verifier} (--optimized, VK_HASH ${m[1].slice(0, 10)}...)`,
    );
    return m[1];
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function main() {
  console.log(
    "--- Generating Solidity Verifiers (native bb 5.0 --optimized) ---",
  );
  try {
    assertNativeBb();
  } catch (e) {
    // --optimized generation is CLI-only; when native bb is absent (CI, bb.js-only dev), keep the committed
    // verifiers + manifest (guarded by VkHashParity) instead of failing the build.
    console.log(`[skip] ${e.message}; keeping committed verifiers.`);
    return;
  }
  if (!existsSync(verifiersDir)) mkdirSync(verifiersDir, { recursive: true });

  const vkHashes = {};
  for (const { name, verifier } of [...CIRCUITS, ...KAGE_CIRCUITS]) {
    if (!verifier) continue;
    vkHashes[name] = generateOne(name, verifier);
  }
  writeFileSync(vkHashManifestPath, JSON.stringify(vkHashes, null, 2) + "\n");
  console.log(`Wrote VK-hash manifest: ${vkHashManifestPath}`);
}

main();
