asset_id = ""
compliance_pubkey_x = ""
compliance_pubkey_y = ""
memo_id = ""
owner_x = ""
owner_y = ""
recipient_sk = ""
salt = ""
sk_out = ""
timelock = ""
val = ""

[note_out]
asset_id = ""
hashlock = ""
nullifier = ""
secret = ""
timelock = ""
value = ""
