asset_id = ""
compliance_pubkey_x = ""
compliance_pubkey_y = ""
current_timestamp = ""
eph = ""
memo_id = ""
owner_x = ""
owner_y = ""
recipient_sk = ""
salt = ""
timelock = ""
val = ""

[note_out]
asset_id = ""
conditions_hash = ""
note_type = ""
note_version = ""
owner = ""
parents = ""
psi = ""
value = ""
