[workspace]
members = [
    "deposit",
    "shared",
    "split",
    "join",
    "withdraw",
    "transfer",
    "public_claim",
    "withdraw_multisig",
    "transfer_multisig",
    "split_multisig",
    "join_multisig",
]
