[workspace]
members = [
    "shared",
    "standard/deposit",
    "standard/withdraw",
    "standard/transfer",
    "standard/split",
    "standard/join",
    "standard/public_claim",
    "multisig/withdraw_multisig",
    "multisig/transfer_multisig",
    "multisig/split_multisig",
    "multisig/join_multisig",
    "kage/kage_lib",
    "kage/pre_swap",
    "kage/recursive_swap",
]
