import { describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import { TIMESTAMP_SKEW_SECONDS, fromHexRaw } from "@hisoka/pss-client/wire";
import {
  accountIdOf,
  ownsAccount,
  verifyEd25519,
  withinSkew,
} from "../auth.js";
import { newAccount } from "./harness.js";

// RFC 8032 section 7.1, TEST 2. The vector is published, not regenerated by the code it checks.
const RFC8032_PUBLIC_KEY =
  "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c";
const RFC8032_MESSAGE = "72";
const RFC8032_SIGNATURE =
  "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da" +
  "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00";

describe("ed25519 verification", () => {
  it("accepts the published RFC 8032 vector", () => {
    expect(
      verifyEd25519(
        fromHexRaw(RFC8032_MESSAGE, "message"),
        fromHexRaw(RFC8032_SIGNATURE, "signature"),
        fromHexRaw(RFC8032_PUBLIC_KEY, "authPk"),
      ),
    ).toBe(true);
  });

  it("rejects the vector under a flipped signature bit or a flipped message bit", () => {
    const signature = fromHexRaw(RFC8032_SIGNATURE, "signature");
    signature[0] ^= 1;
    expect(
      verifyEd25519(
        fromHexRaw(RFC8032_MESSAGE, "message"),
        signature,
        fromHexRaw(RFC8032_PUBLIC_KEY, "authPk"),
      ),
    ).toBe(false);

    const message = fromHexRaw(RFC8032_MESSAGE, "message");
    message[0] ^= 1;
    expect(
      verifyEd25519(
        message,
        fromHexRaw(RFC8032_SIGNATURE, "signature"),
        fromHexRaw(RFC8032_PUBLIC_KEY, "authPk"),
      ),
    ).toBe(false);
  });

  it("rejects a signature made by another key", () => {
    const signer = newAccount();
    const stranger = newAccount();
    const message = Uint8Array.of(1, 2, 3);
    expect(verifyEd25519(message, signer.sign(message), signer.authPk)).toBe(
      true,
    );
    expect(verifyEd25519(message, signer.sign(message), stranger.authPk)).toBe(
      false,
    );
  });

  it("answers false rather than throwing on a malformed key or signature", () => {
    const message = Uint8Array.of(1);
    expect(verifyEd25519(message, new Uint8Array(64), new Uint8Array(0))).toBe(
      false,
    );
    expect(verifyEd25519(message, new Uint8Array(64), new Uint8Array(31))).toBe(
      false,
    );
    expect(
      verifyEd25519(
        message,
        new Uint8Array(0),
        fromHexRaw(RFC8032_PUBLIC_KEY, "authPk"),
      ),
    ).toBe(false);
  });
});

describe("account binding", () => {
  it("derives the account id as the digest of the public key", () => {
    const account = newAccount();
    expect(accountIdOf(account.authPk)).toEqual(
      Uint8Array.from(createHash("sha256").update(account.authPk).digest()),
    );
    expect(ownsAccount(account.authPk, account.accountId)).toBe(true);
  });

  it("refuses a public key that hashes to another account and a short account id", () => {
    const account = newAccount();
    const stranger = newAccount();
    expect(ownsAccount(stranger.authPk, account.accountId)).toBe(false);
    expect(ownsAccount(account.authPk, account.accountId.slice(0, 31))).toBe(
      false,
    );
  });
});

describe("skew window", () => {
  it("is open inside the window and closed on both edges", () => {
    const now = 1_800_000_000;
    expect(withinSkew(now, now, TIMESTAMP_SKEW_SECONDS)).toBe(true);
    expect(
      withinSkew(now + TIMESTAMP_SKEW_SECONDS - 1, now, TIMESTAMP_SKEW_SECONDS),
    ).toBe(true);
    expect(
      withinSkew(now - TIMESTAMP_SKEW_SECONDS + 1, now, TIMESTAMP_SKEW_SECONDS),
    ).toBe(true);
    expect(
      withinSkew(now + TIMESTAMP_SKEW_SECONDS, now, TIMESTAMP_SKEW_SECONDS),
    ).toBe(false);
    expect(
      withinSkew(now - TIMESTAMP_SKEW_SECONDS, now, TIMESTAMP_SKEW_SECONDS),
    ).toBe(false);
  });
});
