// Published cross-check vectors. These are NOT regenerated by the code under test: each value is
// transcribed from the standards document named beside it, so a primitive that is self-consistently
// wrong still fails here.
//
// RFC 5869 appendix A   https://www.rfc-editor.org/rfc/rfc5869.txt
// RFC 8032 section 7.1  https://www.rfc-editor.org/rfc/rfc8032.txt
// NIST CAVP GCMVS       gcmEncryptExtIV256.rsp in
//                       https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/mac/gcmtestvectors.zip

export interface HkdfVector {
  readonly name: string;
  readonly ikm: string;
  readonly salt: string;
  readonly info: string;
  readonly length: number;
  readonly prk: string;
  readonly okm: string;
}

export interface Ed25519Vector {
  readonly name: string;
  readonly seed: string;
  readonly publicKey: string;
  readonly message: string;
  readonly signature: string;
}

export interface AesGcmVector {
  readonly name: string;
  readonly key: string;
  readonly iv: string;
  readonly plaintext: string;
  readonly aad: string;
  readonly ciphertext: string;
  readonly tag: string;
}

// PRK is the HKDF-Extract output; OKM is HKDF-Expand(PRK, info, L). PSS derives with Expand only, so the
// Expand half of each case is what pins the implementation. Extract is carried to keep the case complete.
export const RFC5869_SHA256: readonly HkdfVector[] = [
  {
    name: "RFC 5869 Test Case 1",
    ikm: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    salt: "000102030405060708090a0b0c",
    info: "f0f1f2f3f4f5f6f7f8f9",
    length: 42,
    prk: "077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5",
    okm: "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865",
  },
  {
    name: "RFC 5869 Test Case 2",
    ikm: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f",
    salt: "606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeaf",
    info: "b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
    length: 82,
    prk: "06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244",
    okm: "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87",
  },
  {
    name: "RFC 5869 Test Case 3",
    ikm: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    salt: "",
    info: "",
    length: 42,
    prk: "19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04",
    okm: "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8",
  },
];

export const RFC8032_ED25519: readonly Ed25519Vector[] = [
  {
    name: "RFC 8032 TEST 1",
    seed: "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
    publicKey:
      "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
    message: "",
    signature:
      "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
  },
  {
    name: "RFC 8032 TEST 2",
    seed: "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
    publicKey:
      "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
    message: "72",
    signature:
      "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
  },
  {
    name: "RFC 8032 TEST 3",
    seed: "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
    publicKey:
      "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
    message: "af82",
    signature:
      "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a",
  },
];

// All five sit under [Keylen = 256] [IVlen = 96], which is the only IV length PSS emits.
export const CAVP_AES_256_GCM: readonly AesGcmVector[] = [
  {
    name: "CAVP 256/96 PTlen=0 AADlen=0 Count=0",
    key: "b52c505a37d78eda5dd34f20c22540ea1b58963cf8e5bf8ffa85f9f2492505b4",
    iv: "516c33929df5a3284ff463d7",
    plaintext: "",
    aad: "",
    ciphertext: "",
    tag: "bdc1ac884d332457a1d2664f168c76f0",
  },
  {
    name: "CAVP 256/96 PTlen=0 AADlen=128 Count=0",
    key: "78dc4e0aaf52d935c3c01eea57428f00ca1fd475f5da86a49c8dd73d68c8e223",
    iv: "d79cf22d504cc793c3fb6c8a",
    plaintext: "",
    aad: "b96baa8c1c75a671bfb2d08d06be5f36",
    ciphertext: "",
    tag: "3e5d486aa2e30b22e040b85723a06e76",
  },
  {
    name: "CAVP 256/96 PTlen=128 AADlen=0 Count=0",
    key: "31bdadd96698c204aa9ce1448ea94ae1fb4a9a0b3c9d773b51bb1822666b8f22",
    iv: "0d18e06c7c725ac9e362e1ce",
    plaintext: "2db5168e932556f8089a0622981d017d",
    aad: "",
    ciphertext: "fa4362189661d163fcd6a56d8bf0405a",
    tag: "d636ac1bbedd5cc3ee727dc2ab4a9489",
  },
  {
    name: "CAVP 256/96 PTlen=128 AADlen=128 Count=0",
    key: "92e11dcdaa866f5ce790fd24501f92509aacf4cb8b1339d50c9c1240935dd08b",
    iv: "ac93a1a6145299bde902f21a",
    plaintext: "2d71bcfa914e4ac045b2aa60955fad24",
    aad: "1e0889016f67601c8ebea4943bc23ad6",
    ciphertext: "8995ae2e6df3dbf96fac7b7137bae67f",
    tag: "eca5aa77d51d4a0a14d9c51e1da474ab",
  },
  {
    name: "CAVP 256/96 PTlen=408 AADlen=720 Count=0",
    key: "148579a3cbca86d5520d66c0ec71ca5f7e41ba78e56dc6eebd566fed547fe691",
    iv: "b08a5ea1927499c6ecbfd4e0",
    plaintext:
      "9d0b15fdf1bd595f91f8b3abc0f7dec927dfd4799935a1795d9ce00c9b879434420fe42c275a7cd7b39d638fb81ca52b49dc41",
    aad: "e4f963f015ffbb99ee3349bbaf7e8e8e6c2a71c230a48f9d59860a29091d2747e01a5ca572347e247d25f56ba7ae8e05cde2be3c97931292c02370208ecd097ef692687fecf2f419d3200162a6480a57dad408a0dfeb492e2c5d",
    ciphertext:
      "2097e372950a5e9383c675e89eea1c314f999159f5611344b298cda45e62843716f215f82ee663919c64002a5c198d7878fd3f",
    tag: "adbecdb0d5c2224d804d2886ff9a5760",
  },
];
