[package]
name = "shared"
type = "lib"
authors = ["hisoka-io"]
license = "Apache-2.0"

[dependencies]
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }
ecdh = { tag = "ecdh-v0.0.2-hisoka.1", git = "https://github.com/hisoka-io/zk-kit.noir", directory = "packages/ecdh" }
edwards = { tag = "v0.2.5-hisoka.1", git = "https://github.com/hisoka-io/noir-edwards" }