[package]
name = "swap_settle"
type = "bin"
authors = ["hisoka-io"]
license = "Apache-2.0"

[dependencies]
kage_lib = { path = "../kage_lib" }
shared = { path = "../../shared" }
ecdh = { path = "../../vendor/ecdh" }
