[package]
name = "swap_settle"
type = "bin"
authors = ["hisoka-io"]
license = "Apache-2.0"

[dependencies]
kage_lib = { path = "../kage_lib" }
shared = { path = "../../shared" }
ecdh = { tag = "ecdh-v0.0.2-hisoka.1", git = "https://github.com/hisoka-io/zk-kit.noir", directory = "packages/ecdh" }
